name: NodeJs CI


on:

push:

branches: ["main"]
pull_request:
branches: ["main"]

workflow_dispatch:

jobs:

build:

runs-on: ubuntu-latest

steps:

-uses: actions/checkout@v4

-uses: actions/setup-node@v4

-name: Install dependencies
run: npm install

-name: run test
run: npm test
